packages:
  core: !include guition-esp32-p4-jc8012p4a1.yaml

esphome:
  project:
    name: nnmalex.esp32-dash
    version: dev

dashboard_import:
  package_import_url: github://nnmalex/esp32-dash/guition-esp32-p4-jc8012p4a1/esphome.yaml@main
