substitutions:
  name: "esp32-dash-dev"
  friendly_name: "ESP32 Dash Dev"
  # 270° landscape (flipped)
  display_rotation: "270"
  touch_mirror_x: "true"
  touch_mirror_y: "true"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

packages:
  music_dashboard: !include packages.yaml

external_components:
  - source:
      type: local
      path: ../components
    components: [online_image]
